### ISSUE TITLE
Allow instantiating Parsable with verbose=False

### ISSUE THREAD

**Issue by fsaad** [fritzo/parsable#2]
Suppressing the command and runtime report:

https://github.com/fritzo/parsable/blob/master/parsable.py#L67-L68
https://github.com/fritzo/parsable/blob/master/parsable.py#L106

The end-user can always manually redirect stderr. However, a user in python who is creating Parsable objects to expose module-level functions to the command line could conceivably wish to suppress these two stderr reports all together, without relying on the end-user to do redirections.

**Comment by fritzo** [comment]
Sounds reasonable. What do you think if I let this be an environment variable that defaults to non-verbose?

**Comment by fsaad** [comment]
An environment variable e.g. `PARSABLE_VERBOSE` is a good solution as well.

**Comment by fritzo** [comment]
Fixed by #3 and now available on PyPI as version 0.2.3
